-- PostgreSQL Schema for Virtual Assistant Bot
-- This schema will be auto-generated by Hibernate, but this file serves as documentation

CREATE TABLE IF NOT EXISTS user_profiles (
    chat_id BIGINT PRIMARY KEY,
    telegram_username VARCHAR(255),
    display_name VARCHAR(100),
    language VARCHAR(20) DEFAULT 'ENGLISH',
    favourite_city VARCHAR(100) DEFAULT 'Chernivtsi',
    base_currency VARCHAR(3) DEFAULT 'USD',
    target_currency VARCHAR(3) DEFAULT 'UAH',
    created_at BIGINT,
    updated_at BIGINT
);

-- Index for faster username lookups
CREATE INDEX IF NOT EXISTS idx_user_profiles_username ON user_profiles(telegram_username);

-- Comments
COMMENT ON TABLE user_profiles IS 'Stores user profile information and preferences';
COMMENT ON COLUMN user_profiles.chat_id IS 'Telegram chat ID - unique identifier for the user';
COMMENT ON COLUMN user_profiles.telegram_username IS 'Telegram username (optional)';
COMMENT ON COLUMN user_profiles.display_name IS 'User display name';
COMMENT ON COLUMN user_profiles.language IS 'Preferred language: ENGLISH or UKRAINIAN';
COMMENT ON COLUMN user_profiles.favourite_city IS 'Default city for weather queries';
COMMENT ON COLUMN user_profiles.base_currency IS 'Default base currency for exchange rate queries';
COMMENT ON COLUMN user_profiles.target_currency IS 'Default target currency for exchange rate queries';

