-- PostgreSQL Schema for Virtual Assistant Bot
-- This schema will be auto-generated by Hibernate, but this file serves as documentation

CREATE TABLE IF NOT EXISTS user_profiles (
    chat_id BIGINT PRIMARY KEY,
    telegram_username VARCHAR(255),
    display_name VARCHAR(100),
    language VARCHAR(20) DEFAULT 'ENGLISH',
    favourite_city VARCHAR(100) DEFAULT 'Chernivtsi',
    base_currency VARCHAR(3) DEFAULT 'USD',
    target_currency VARCHAR(3) DEFAULT 'UAH',
    created_at BIGINT,
    updated_at BIGINT
);

-- Index for faster username lookups
CREATE INDEX IF NOT EXISTS idx_user_profiles_username ON user_profiles(telegram_username);

-- Comments
COMMENT ON TABLE user_profiles IS 'Stores user profile information and preferences';
COMMENT ON COLUMN user_profiles.chat_id IS 'Telegram chat ID - unique identifier for the user';
COMMENT ON COLUMN user_profiles.telegram_username IS 'Telegram username (optional)';
COMMENT ON COLUMN user_profiles.display_name IS 'User display name';
COMMENT ON COLUMN user_profiles.language IS 'Preferred language: ENGLISH or UKRAINIAN';
COMMENT ON COLUMN user_profiles.favourite_city IS 'Default city for weather queries';
COMMENT ON COLUMN user_profiles.base_currency IS 'Default base currency for exchange rate queries';
COMMENT ON COLUMN user_profiles.target_currency IS 'Default target currency for exchange rate queries';

-- Reminders table for storing user reminders
CREATE TABLE IF NOT EXISTS reminders (
    id BIGSERIAL PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    reminder_text VARCHAR(1000) NOT NULL,
    reminder_date_time TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    notified BOOLEAN DEFAULT FALSE NOT NULL
);

-- Index for faster reminder lookups by chat_id
CREATE INDEX IF NOT EXISTS idx_reminders_chat_id ON reminders(chat_id);

-- Index for finding due reminders efficiently
CREATE INDEX IF NOT EXISTS idx_reminders_due ON reminders(reminder_date_time, notified);

COMMENT ON TABLE reminders IS 'Stores user reminders with scheduled notification times';
COMMENT ON COLUMN reminders.id IS 'Unique identifier for the reminder';
COMMENT ON COLUMN reminders.chat_id IS 'Telegram chat ID of the user who created the reminder';
COMMENT ON COLUMN reminders.reminder_text IS 'The text/message of the reminder';
COMMENT ON COLUMN reminders.reminder_date_time IS 'When the reminder should be triggered';
COMMENT ON COLUMN reminders.created_at IS 'When the reminder was created';
COMMENT ON COLUMN reminders.notified IS 'Whether the notification has been sent';

-- Events table for storing calendar events
CREATE TABLE IF NOT EXISTS events (
    id BIGSERIAL PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    title VARCHAR(500) NOT NULL,
    start_date_time TIMESTAMP NOT NULL,
    end_date_time TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    notified BOOLEAN DEFAULT FALSE NOT NULL
);

-- Index for faster event lookups by chat_id
CREATE INDEX IF NOT EXISTS idx_events_chat_id ON events(chat_id);

-- Index for finding due events efficiently
CREATE INDEX IF NOT EXISTS idx_events_due ON events(start_date_time, notified);

COMMENT ON TABLE events IS 'Stores calendar events with start and end times';
COMMENT ON COLUMN events.id IS 'Unique identifier for the event';
COMMENT ON COLUMN events.chat_id IS 'Telegram chat ID of the user who created the event';
COMMENT ON COLUMN events.title IS 'The title/name of the event';
COMMENT ON COLUMN events.start_date_time IS 'When the event starts';
COMMENT ON COLUMN events.end_date_time IS 'When the event ends';
COMMENT ON COLUMN events.created_at IS 'When the event was created';
COMMENT ON COLUMN events.notified IS 'Whether the notification has been sent';
